# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30526cee4e0f98e4a0cfddc8ea6aa9c05ae7cb4c2d6aeabb4f237444a14923bc7b1765b781ee1d5bfb7574558b8125e9027902a1aa097ebb3e6215a8cc7e99c4

test:
  secret_key_base: cc81870a667103f00729246ba4373d434c0716632fa8fc89e4d06d7323ef18bf80ea6229a534d00cbdadd71ed904d8426588147d1f106b3593d149c2b923011c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
